### ISSUE TITLE
Polyfills

### ISSUE THREAD

**Issue by hemanth** [DavidBruant/Map-Set.prototype.toJSON#4]
Hello @DavidBruant gave a try on poly-filling these as specified in the spec.

Do have a look at them:
- [Map.prototype.toJSON](https://github.com/hemanth/Map.prototype.toJSON)
- [Set.prototype.toJSON](https://github.com/hemanth/Set.prototype.toJSON)

**Comment by DavidBruant** [comment]
Wow, super cool! Thanks for this :-)
I'm a bit swamped by other things right now, but I'll add the links to the proposal (keeping the issue open to remember to address it).
Maybe you'll want to coordinate with @ljharb who working on something like that as well.

**Comment by hemanth** [comment]
@DavidBruant Such a small world ;) @ljharb is a friend of mine :smile: and yeah he is too good with it!

**Comment by ljharb** [comment]
I'm still going to be creating my own for inclusion into the es7-shim, since they need to follow strict conventions, so it's unfortunate that the names have been claimed, but it's good to have reference implementations.

**Comment by hemanth** [comment]
:+1: I would contribute to them ;) 

I agree these are not adhered to the conventions so marked them with minor versions.

**Comment by ljharb** [comment]
I've just published https://www.npmjs.com/package/map-tojson and https://www.npmjs.com/package/set-tojson, as well as included them in https://www.npmjs.com/package/es7-shim

This incorporates the "entries" changes to `Map#toJSON`, and makes some hopefully educated guesses about the reusability of both `toJSON` functions. Note that it would _much_ easier to implement them such that they throw when not given a true `Map` or `Set` respectively, otherwise, the spec will need detailed steps so that both `Map#toJSON` and `Set#toJSON` give reliable and consistent output when `call`ed with a `Map`, a `Set`, an array, an array-like object, a string, something non-iterable, etc.

**Comment by monolithed** [comment]
`Array.from` does the same.
We need result like `JSON.stringify`:

```
let map = new Map;
map.set(0, 1);
map.toJSON; // {0, 1}
```

Or 

``` js
Object.from(map);
```

**Comment by ljharb** [comment]
What's `{0, 1}`? `Array.from(map)` would return the same thing as `map.toJSON()`, because `map[Symbol.iterator]` is `Map#entries` which is the same as `Map#toJSON` - I think the consistency is pretty elegant.

**Comment by monolithed** [comment]
Sorry, I meant `{0: 1}`

**Comment by tomByrer** [comment]
Babel seems to support this, though I have not personally tested yet.
http://kangax.github.io/compat-table/es7/

**Comment by zloirock** [comment]
@tomByrer [`core-js` supports it](https://github.com/zloirock/core-js#ecmascript-7) -> [`babel` supports it](http://babeljs.io/docs/usage/polyfill/).
